steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/resounding-rune-428908-p8/datalab2/hello-world:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/resounding-rune-428908-p8/datalab2/hello-world:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/hello-server'
  - 'hello-world=us-east1-docker.pkg.dev/resounding-rune-428908-p8/datalab2/hello-world:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
images:
- 'us-east1-docker.pkg.dev/resounding-rune-428908-p8/datalab2/hello-world:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
