apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world
        image: us-east1-docker.pkg.dev/resounding-rune-428908-p8/datalab2/hello-world:latest
        env:
          - name: DB_NAME
            value: postgres
          - name: DB_USER
            value: postgres
